# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  sapsocleague-app:
    image: henrybrooks/sapsoc
    environment:
      - _JAVA_OPTIONS=-Xmx128m -Xms64m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://sapsocleague-postgresql:5432/SapsocLeague
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://sapsocleague-postgresql:5432/SapsocLeague
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 8080:8080
  sapsocleague-postgresql:
    image: postgres:14.5
    # volumes:
    #   - ~/volumes/jhipster/SapsocLeague/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=SapsocLeague
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:5432:5432
